<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>RePKG</RootNamespace>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>net472;net8.0</TargetFrameworks>
        <Version>4.1.0</Version>
        <Copyright>Copyright © NotScuffed 2025</Copyright>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\RePKG.Application\RePKG.Application.csproj" />
        <ProjectReference Include="..\RePKG.Core\RePKG.Core.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="CommandLineParser" Version="2.9.1" />
    </ItemGroup>
    
    <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
        <Reference Include="Microsoft.CSharp" />
    </ItemGroup>

    <ItemGroup>
        <None Include="$(ProjectDir)/../THIRD-PARTY-NOTICES.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    </ItemGroup>
</Project>
